# Generated by Django 5.2.1 on 2025-06-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
