# Generated by Django 5.2.1 on 2025-06-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_alter_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
